name: docker deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'crustio/ethda-home'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run install
        run: pnpm install --frozen-lockfile

      - name: Build for production
        run: pnpm build

      - name: Build docker and publish
        run: |
          docker build -t crustio/ethda-home:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push crustio/ethda-home:latest
      - name: Update docker compose
        uses: fifsky/ssh-action@master
        with:
          command: ${{ secrets.RUN_CMD }}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        
