name: Github Pages Beta Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    if: github.repository == 'crustio/ethda-home'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'
          

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run install
        run: pnpm install --frozen-lockfile

      - name: Build for production
        run: pnpm build


      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_BETA }}
          external_repository: crustio/ethda-home-site-beta
          publish_branch: main
          publish_dir: ./out
          cname: beta.ethda.io